In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr0 = np.array(42)

print(arr0)

print(arr0.ndim)


42
0


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2.ndim)

print(arr2)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3.ndim)

print(arr3)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print('2nd element on 1st row: ', arr2[0, 1])
print('last element on 2nd row: ', arr2[1, -1])


2nd element on 1st row:  2
last element on 2nd row:  6


In [ ]:
print(arr3[0, 1, 2])

6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4:2])

[7 8 9]
[3 8]
[[2 4]
 [7 9]]


In [ ]:
print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6
